<h1><center>Laboratorio 3: El Pandas no muerde (act. I) 🐼</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos</strong></center>

---

### Cuerpo Docente

- Profesores: Pablo Badilla y Diego Cortez
- Auxiliares: Valentina Rojas y Melanie Peña
- Ayudantes: Javiera Arévalo, Tamara Carrasco y Ignacio Reyes


### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: ISADORA MADRID


---

### Reglas

- **Grupos de 2 personas**
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibido copiar.
- Uso de LLM (Copilot, Claude, Antigravity, Cursor, etc.) restringido a consultas, documentación y corrección de errores. 

### Objetivos

- Entender, aplicar y aprovechar las ventajas que nos ofrece la libreria `pandas` para manejar datos tabulares.
- Aprender a utilizar la documentación de pandas (y en general, de cualquier librería de python) como también a buscar soluciones en la web.

> ⚠️ **Importante**: El laboratorio deberá ser desarrollado sin el uso de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`.

### Librerias utiles para el Lab 😸

In [ ]:
!pip install pandas plotly

  Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------  9.7/9.9 MB 86.6 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 44.3 MB/s  0:00:00
Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)

   ---------------------------------------- 0/6 [pytz]
   ---------------------------------------- 0/6 [pytz]
   ---------------------------------------- 0/6 [pytz]
   ---------------------------------------- 0/6 [pytz]
   ---------------------------------------- 0/6 [pytz]
   ---------------------------------------- 0/6 [pytz]
   ---------------------------------------- 0/6 [pytz]
   --

In [3]:
import pandas as pd
import plotly.express as px

---

# 1. Rendimiento en Estudiantes 📚

### 📊 Sobre los datos

El objetivo principal será realizar un trabajo de limpieza y preparación de datos utilizando exclusivamente DataFrames y las herramientas asociadas a estos. 

Para esto deberán trabajar con el dataset `students_grades.json`, el cual pueden descargar desde la siguiente URL:

> https://raw.githubusercontent.com/MDS7202/MDS7202/refs/heads/main/recursos/2026-01/labs/lab3/students_grades.json

El dataset contiene información sobre el rendimiento de alumnos en distintos ramos. Cada fila representa un estudiante con las siguientes columnas:

- `names`: Nombre del estudiante
- `gender`: Género
- `race/ethnicity`: Grupo étnico
- `parental level of education`: Nivel educacional de los padres
- `lunch`: Tipo de almuerzo (estándar o reducido)
- `test preparation course`: Si completó curso de preparación
- `math score`: Nota de matemáticas (escala 0-100)
- `reading score`: Nota de lectura (escala 0-100)
- `writing score`: Nota de escritura (escala 0-100)


**Nota sobre GPA**: En el contexto educativo anglosajón, GPA (*Grade Point Average*) se refiere al promedio general de calificaciones.

---

## 1.1 Revisión de datos 🔎 [1.2 puntos]

<p align="center">
  <img src="https://media2.giphy.com/media/4FQMuOKR6zQRO/giphy.gif?cid=ecf05e47ii9lhu9tc9tb31d6lafrysp2zyf6u8w3y348mk8t&rid=giphy.gif&ct=g">
</p>


*Don Caguayo*, rector de la Universidad de la Cachaña, les comenta que actualmente la Universidad no tiene una subdirección de análisis de datos, pero que tiene interés en formar una. Es por esto, que se contacta con ud. y su equipo para iniciar de forma exploratoria diversas tareas de análisis y consolidación de datos respectivos al rendimiento de sus alumnos.

En su primera reunión, el rector les comenta que la sección de TI posee una base de datos con más de **1000** filas, en donde cada fila representa un alumno matriculado. Sin embargo, cree fuertemente que existen errores en esta: solo tiene registro de **1000** matriculas. Por este motivo, especula que se han realizado malas prácticas al inscribir dichos datos.


En consecuencia, el rector les solicita a ustedes como tarea inicial que exploren la base de datos y encuentre posibles falencias dentro de sus registros. Para esto, usted debe estar al tanto que las notas (GPA) están en una escala que van del **0 al 100** (porcentaje de logro) y **no es posible que un alumno aparezca más de una vez, ya que las notas son promedios de sus asignaturas**. 

Cualquier alumno que posea un valor diferente a esta escala, debería ser eliminado de la base de datos.


> **Instrucciones**

Implemente la función `analyze_df` que tome un `DataFrame` y que le permita generar diversos análisis que permitan observar estadísticas y anomalías de las diferentes variables que componen este dataset.

**To-Do**
1. [ ] Imprimir un mensaje con las dimensiones del Dataframe. [0.1 puntos]
2. [ ] Imprimir un mensaje con los nombres de las columnas que conforman el DataFrame. [0.1 puntos]
3. [ ] Mostrar los primeros 5, los últimos 5 elementos del DataFrame y realice un muestreo de 5 elementos de forma aleatoria. [0.1 puntos]
4. [ ] Mostrar una descripción rápida de las variables numéricas del DataFrame (utilice un método visto en clases). [0.1 puntos]
5. [ ] Imprimir un mensaje con la cantidad de valores nulos (investigue el método `isna()` y `sum()` de los DataFrames). [0.1 puntos]
6. [ ] Imprimir un mensaje que detalle la cantidad de valores unicos (investigue `nunique()`) . [0.1 puntos]
7. [ ] Imprimir un mensaje con el total de filas que contengan nombres duplicados (investigue `duplicated()` y su parámetro `subset`). [0.1 puntos]
8. [ ] Mostrar las filas que contengan nombres sean duplicados (investigue `duplicated()` y su parámetro `subset`). [0.1 puntos]
9. [ ] A través de `px.histogram(col_name, title="Título").show()` graficar el histograma de cada tipo de nota (`math score`, `reading score`, `writing score`). Investigue cómo funcionan los histogramas si es necesario. [0.2 puntos]
10. [ ] Responda las preguntas en la celda correspondiente. [0.2 puntos]

> **Nota:** Para imprimir utilice `print(...)`. Para mostrar `DataFrames`, utilice `display(...)` ya que este permite mostrar estos elementos como tablas.

> **Nota 2:** Utilice la documentación de [pandas](https://pandas.pydata.org/docs/index.html) como también StackOverflow para resolver cualquier problema o inconveniente.

**Respuesta Código:**

In [8]:
# Primero deberan cargar los datos usando un lector apropiado
url = "https://raw.githubusercontent.com/MDS7202/MDS7202/refs/heads/main/recursos/2026-01/labs/lab3/students_grades.json"

df_grades = pd.read_json(url)

display(df_grades)

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37,46,46
1,Madeline Fuller,female,group C,some high school,standard,none,124,142,142
2,Daniel Rester,male,group E,associate's degree,standard,none,156,196,193
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80,78,81
4,Geraldine Hale,female,group A,associate's degree,standard,none,131,166,166
...,...,...,...,...,...,...,...,...,...
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193,142,193
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66,74,81
1397,Laurie Carter,female,group B,some high school,standard,completed,54,61,62
1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193,196,193


In [11]:
!pip install nbformat


   ---------------------------------------- 0/7 [fastjsonschema]
   ----------- ---------------------------- 2/7 [attrs]
   ----------- ---------------------------- 2/7 [attrs]
   ----------------- ---------------------- 3/7 [referencing]
   ----------------- ---------------------- 3/7 [referencing]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------------- 7/7 [nbformat]



In [13]:
#Realizamos paso a paso el TO DO
def analyze_df(df: pd.DataFrame) -> None:
    
    # 1. Dimensiones
    print("Dimensiones del DataFrame:", df.shape)
    
    # 2. Columnas
    print("\nColumnas:")
    print(df.columns.tolist())
    
    # 3. Primeros, últimos y sample
    print("\nPrimeros 5:")
    display(df.head())
    
    print("\nÚltimos 5:")
    display(df.tail())
    
    print("\nSample aleatorio:")
    display(df.sample(5))
    
    # 4. Descripción numérica
    print("\nDescripción variables numéricas:")
    display(df.describe())
    
    # 5. Valores nulos
    print("\nValores nulos por columna:")
    print(df.isna().sum())
    
    # 6. Valores únicos
    print("\nValores únicos por columna:")
    print(df.nunique())
    
    # 7. Cantidad de duplicados por nombre
    duplicados = df.duplicated(subset=["names"]).sum()
    print("\nCantidad de nombres duplicados:", duplicados)
    
    # 8. Mostrar duplicados
    print("\nFilas con nombres duplicados:")
    display(df[df.duplicated(subset=["names"], keep=False)])
    
    # 9. Histogramas
    columnas_notas = ["math score", "reading score", "writing score"]
    
    for col in columnas_notas:
        fig = px.histogram(df, x=col, title=f"Histograma de {col}")
        fig.show()

In [14]:
analyze_df(df_grades)

Dimensiones del DataFrame: (1400, 9)

Columnas:
['names', 'gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']

Primeros 5:


,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37,46,46
1,Madeline Fuller,female,group C,some high school,standard,none,124,142,142
2,Daniel Rester,male,group E,associate's degree,standard,none,156,196,193
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80,78,81
4,Geraldine Hale,female,group A,associate's degree,standard,none,131,166,166



Últimos 5:


,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193,142,193
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66,74,81
1397,Laurie Carter,female,group B,some high school,standard,completed,54,61,62
1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193,196,193
1399,Amanda Perez,female,group A,high school,standard,completed,68,80,76



Sample aleatorio:


,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
269,Shawn Lopez,male,group D,some college,standard,completed,58,59,58
1112,Thomas Ronzoni,male,group C,associate's degree,standard,completed,51,60,58
343,Jeremy Smith,male,group D,some high school,standard,completed,193,124,142
926,Luis Lichty,male,group A,high school,standard,none,59,52,46
1158,Robert Frazier,male,group D,high school,free/reduced,completed,142,193,193



Descripción variables numéricas:


,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
count,1400,1400,1400,1400,1400,1400,1400,1400,1400
unique,1153,2,5,6,2,2,97,89,93
top,Robert Frazier,female,group C,some college,standard,none,193,193,193
freq,3,723,452,334,904,898,120,117,133



Valores nulos por columna:
names                          0
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

Valores únicos por columna:
names                          1153
gender                            2
race/ethnicity                    5
parental level of education       6
lunch                             2
test preparation course           2
math score                       97
reading score                    89
writing score                    93
dtype: int64

Cantidad de nombres duplicados: 247

Filas con nombres duplicados:


,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37,46,46
5,Brian Young,male,group C,some high school,standard,none,73,66,63
6,Howard Jimenez,male,group E,some high school,standard,completed,81,75,76
8,Jonathan Clingan,male,group D,some college,standard,completed,71,61,69
10,Nancy Bassett,female,group C,high school,standard,none,124,196,193
...,...,...,...,...,...,...,...,...,...
1385,James Crawford,male,group D,master's degree,standard,none,193,147,131
1390,Gloria Bradford,female,group B,high school,standard,none,124,64,193
1393,Adam Romero,male,group C,high school,standard,completed,124,193,49
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193,142,193


ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

**Preguntas ❓:**

> ¿Qué anomalías es posible observar de los datos que componen el DataFrame? 

> ¿Existen valores nulos o duplicados? ¿Qué puede interpretar de la distribución de las notas en los histogramas?


**Respuestas 📝:**

```
En el DF se pueden observar varias anomalías importantes que afectan la calidad de los datos. En primer lugar, existen valores fuera de rango en las variables de notas (math score, reading score y writing score), ya que estas deberían encontrarse en una escala de 0 a 100, pero se identifican valores superiores como 124, 156 e incluso cercanos a 200. Esto indica un error claro en el registro o procesamiento de la información. Además, se detecta la presencia de registros duplicados, evidenciado por la existencia de 247 nombres repetidos, lo cual es inconsistente dado que cada estudiante debería aparecer una única vez en la base de datos. Por otra parte, no se observan valores nulos en el dataset, lo cual es positivo en términos de completitud de la información. 

En cuanto a la distribución de las notas observada en los histogramas, se aprecia que la mayor parte de los valores se concentra en un rango entre 50 y 90, lo que sugiere un rendimiento promedio moderado de los estudiantes. No obstante, también se identifica una concentración de valores anormalmente altos, por sobre 120 e incluso cercanos a 200, lo cual rompe la forma esperada de la distribución y genera una asimetría. En condiciones normales, se esperaría una distribución aproximadamente normal dentro del rango definido, por lo que estos valores extremos refuerzan la evidencia de errores en los datos.

```

---

## 1.2 Limpieza de Datos 🫧

<p align="center">
  <img src="https://media3.giphy.com/media/c09yGbnSyaFRS/giphy.gif?cid=ecf05e47d0ejjjnpfj0ywcbwz7zk7sw2rfdpis890gmdpvj2&rid=giphy.gif&ct=g">
</p>


¡Bien! Ya identificaron las anomalías. Ahora es momento de poner manos a la obra y limpiar esos datos. 🧹

En base a lo realizado anteriormente, realice una limpieza del dataset. Asuma los supuestos señalados en la pregunta anterior para limpiar el DataFrame y cree una función que le permita limpiar los datos. Una vez limpiado, compruebe nuevamente los datos con la función creada en la sección 1.1.

**To-Do:**

- [ ] Crear función que permita limpiar el dataset.
  - [ ] Cambiar el nombre de las columnas a snake case (Hint: implementar util `to_snake_case` usando métodos de strings + list/dict comprehension). [0.1 puntos]
  - [ ] Eliminar la palabra `race` de la columna `race/ethnicity` (Hint: `rename`) [0.1 puntos]
  - [ ] Eliminar datos duplicados [0.2 puntos]
  - [ ] Forzar tipos de las columnas con score a float con `pd.to_numeric, errors="coerce")` (Hint: coerce dejará como nulos los valores que no sean floats, importante para el siguiente paso)[0.2 puntos]
  - [ ] Eliminar datos nulos [0.2 puntos]
  - [ ] Eliminar registros con notas anómalas (> 100, < 0) [0.2 puntos]
- [ ] Comprobar que ya no existen anomalías en los datos usando la función de la sección 1.1 (solo imprimir, no justificar). Puede que necesite adaptar la función para usar los nuevos nombres de columnas

**Respuesta:**

In [12]:
def to_snake_case(s: str) -> str:
    return s.lower().replace(" ", "_")

In [ ]:
def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    
    df = df.copy()
    
    # 1. snake_case columnas
    df.columns = [to_snake_case(col) for col in df.columns]
    
    # 2. renombrar race/ethnicity → ethnicity
    df = df.rename(columns={"race/ethnicity": "ethnicity"})
    
    # 3. eliminar duplicados COMPLETOS (no solo por nombre) osino hay problemas
    df = df.drop_duplicates()
    
    # 4. convertir scores a numérico
    score_cols = ["math_score", "reading_score", "writing_score"]
    df[score_cols] = df[score_cols].apply(pd.to_numeric, errors="coerce")
    
    # 5. eliminar valores fuera de rango
    df = df[
        df["math_score"].between(0, 100) &
        df["reading_score"].between(0, 100) &
        df["writing_score"].between(0, 100)
    ]
    
    # 6. eliminar nulos
    df = df.dropna()
    
    return df

In [24]:
df_cleaned = clean_data(df_grades)
df_cleaned

print("Dimensiones después de limpieza:", df_cleaned.shape)

Dimensiones después de limpieza: (1000, 9)


> Utilice la función creada en el punto 1.1 para verificar sus resultados. Adapte los nombres de las columnas con snake_case si es necesario.

In [26]:
def analyze_df(df: pd.DataFrame) -> None:
    
    print("Dimensiones del DataFrame:", df.shape)
    
    print("\nColumnas:")
    print(df.columns.tolist())
    
    print("\nPrimeros 5:")
    display(df.head())
    
    print("\nÚltimos 5:")
    display(df.tail())
    
    print("\nSample aleatorio:")
    display(df.sample(5))
    
    print("\nDescripción variables numéricas:")
    display(df.describe())
    
    print("\nValores nulos por columna:")
    print(df.isna().sum())
    
    print("\nValores únicos por columna:")
    print(df.nunique())
    
    duplicados = df.duplicated(subset=["names"]).sum()
    print("\nCantidad de nombres duplicados:", duplicados)
    
    print("\nFilas con nombres duplicados:")
    display(df[df.duplicated(subset=["names"], keep=False)])
    
    columnas_notas = ["math_score", "reading_score", "writing_score"]
    
    for col in columnas_notas:
        fig = px.histogram(df, x=col, title=f"Histograma de {col}")
        fig.show()

In [27]:
analyze_df(df_cleaned)

Dimensiones del DataFrame: (1000, 9)

Columnas:
['names', 'gender', 'ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course', 'math_score', 'reading_score', 'writing_score']

Primeros 5:


,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0



Últimos 5:


,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0
1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0



Sample aleatorio:


,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
1031,Kevin Ibrahim,male,group A,some high school,free/reduced,none,79.0,82.0,73.0
253,Tanya Favela,female,group D,associate's degree,free/reduced,completed,57.0,74.0,76.0
1134,Carolina White,female,group C,high school,standard,none,76.0,76.0,74.0
21,Donald Dunnings,male,group D,some high school,standard,none,74.0,74.0,72.0
1333,Haydee Kunkel,female,group C,high school,free/reduced,none,62.0,67.0,64.0



Descripción variables numéricas:


,math_score,reading_score,writing_score
count,1000.00000,1000.000000,1000.000000
mean,66.08900,69.169000,68.054000
std,15.16308,14.600192,15.195657
min,0.00000,17.000000,10.000000
25%,57.00000,59.000000,57.750000
50%,66.00000,70.000000,69.000000
75%,77.00000,79.000000,79.000000
max,100.00000,100.000000,100.000000



Valores nulos por columna:
names                          0
gender                         0
ethnicity                      0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

Valores únicos por columna:
names                          1000
gender                            2
ethnicity                         5
parental_level_of_education       6
lunch                             2
test_preparation_course           2
math_score                       81
reading_score                    72
writing_score                    77
dtype: int64

Cantidad de nombres duplicados: 0

Filas con nombres duplicados:


,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score


**✅ Checkpoint**: Después de la limpieza deberías tener exactamente 1000 filas


---

## 1.3 Creando y Estructurando Datos 📊



<p align="center">
  <img src="https://media4.giphy.com/media/ko7twHhomhk8E/giphy.gif?cid=ecf05e47xmgfz8ftaom8saa4cwktxpb0fkui9yk3nakb4ff1&rid=giphy.gif&ct=g">
</p>

¡Perfecto! Ya tenemos datos limpios y confiables. Ahora Don Caguayo quiere que le ayudemos a generar nuevas columnas y realizar análisis más profundos. 📊

---

### 1.3.1 Transformación de notas a "Nota Chilena" 🇨🇱 

En una de las reuniones con Don Caguayo, este les comenta su intención de pasar todas sus notas a la "Escala Chilena". Para esto les facilita la siguiente ecuación:

$$Nota \, Chilena= \% \, de \, logro \times 0.06 + 1$$

Utilizando la ecuación entregada, cree una función que le permita transformar las notas (que están en escala 0-100) a la escala chilena [1,7] y entregue las notas redondeadas al segundo decimal.

**To-Do**

- [ ] Implementa la función `to_chilean_grade` que toma un **DataFrame** y el nombre de una **columna** con notas en escala 0-100, y retorna una **Serie** con las notas transformadas a escala chilena (rango 1.0-7.0). [0.3 puntos]
- [ ] Agrega las nuevas series de notas de matemáticas (columna `math_score_cl`), lectura (columna `reading_score_cl`) y escritura (columna `writing_score_cl`) al dataframe `df_cleaned`. [0.3 puntos]


**Respuesta Código:**

In [28]:
# En esta celda implementa la operación solicitada
def to_chilean_grade(df: pd.DataFrame, columna: str) -> pd.Series:
    return (df[columna] * 0.06 + 1).round(2)

In [29]:
# En esta celda ejecuta la función y luego usa indexadores para agregar las nuevas columnas al dataframe limpio
df_cleaned["math_score_cl"] = to_chilean_grade(df_cleaned, "math_score")
df_cleaned["reading_score_cl"] = to_chilean_grade(df_cleaned, "reading_score")
df_cleaned["writing_score_cl"] = to_chilean_grade(df_cleaned, "writing_score")

display(df_cleaned.head())

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,math_score_cl,reading_score_cl,writing_score_cl
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0,3.22,3.76,3.76
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0,5.80,5.68,5.86
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0,5.38,4.96,4.78
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0,5.86,5.50,5.56
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0,6.64,6.16,6.22


---

### 1.3.2 Promedios 📋 [0.3 puntos]

Con todas las notas transformadas, la prestigiosa Universidad De la Cachaña necesita obtener el promedio general (GPA) de cada uno de los alumnos. Para esto se le solicita que calcule el promedio de las tres asignaturas y lo anexe como una nueva columna al DataFrame. 

Cabe señalar que las notas promedio deben ser **redondeadas** al segundo decimal.

**To-Do:**
- [ ] Implementa la función `calculate_average` que dado un dataframe con las notas por alumno, calcula y retorna dos **Series**: una con el promedio de las notas originales (escala 0-100) y otra con el promedio de las notas chilenas.
- [ ] Ejecuta la función y luego, usando indexadores apropiados, agrega las columnas `mean` (promedio escala 0-100) y `mean_cl` (promedio escala chilena) a `df_cleaned`.


**Respuesta:**

In [31]:
# En esta celda implementa la operación solicitada
def calculate_average(df: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
    
    # promedio escala original
    mean = df[["math_score", "reading_score", "writing_score"]].mean(axis=1).round(2)
    
    # promedio escala chilena
    mean_cl = df[["math_score_cl", "reading_score_cl", "writing_score_cl"]].mean(axis=1).round(2)
    
    return mean, mean_cl

In [32]:
# En esta celda ejecuta la función y luego usa indexadores para agregar la nueva columna al dataframe limpio
mean, mean_cl = calculate_average(df_cleaned)

df_cleaned["mean"] = mean
df_cleaned["mean_cl"] = mean_cl

display(df_cleaned.head())

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,math_score_cl,reading_score_cl,writing_score_cl,mean,mean_cl
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0,3.22,3.76,3.76,43.00,3.58
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0,5.80,5.68,5.86,79.67,5.78
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0,5.38,4.96,4.78,67.33,5.04
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0,5.86,5.50,5.56,77.33,5.64
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0,6.64,6.16,6.22,89.00,6.34


---

### 1.3.3 Rankings 📶 [0.4 puntos]

¡Excelente trabajo calculando los promedios! Ahora Don Caguayo quiere saber quiénes son los estudiantes top y generar un ranking general.

**To-Do:**
- [ ] Implementa la función `rank_students` que dado un dataframe con las notas por alumno, obtiene una **Serie** con el ranking de alumnos, de mejor a peor nota (usando el promedio chileno `mean_cl`).
- [ ] Ejecuta la función y luego, usando indexadores apropiados, agrega la columna `rank` al `df_cleaned`.


In [33]:
# En esta celda implementa la operación solicitada
def rank_students(df: pd.DataFrame) -> pd.Series:
    return df["mean_cl"].rank(ascending=False, method="min")

In [34]:
# En esta celda ejecuta la función y luego usa indexadores para agregar la nueva columna al dataframe limpio
df_cleaned["rank"] = rank_students(df_cleaned)

display(df_cleaned.head())

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,math_score_cl,reading_score_cl,writing_score_cl,mean,mean_cl,rank
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0,3.22,3.76,3.76,43.00,3.58,960.0
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0,5.80,5.68,5.86,79.67,5.78,199.0
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0,5.38,4.96,4.78,67.33,5.04,534.0
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0,5.86,5.50,5.56,77.33,5.64,255.0
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0,6.64,6.16,6.22,89.00,6.34,59.0


**Preguntas ❓:**


1. ¿Qué pasa si hay alumnos con el mismo promedio? 
2. ¿Cómo se debería manejar el ranking en ese caso? 
3. ¿Qué parámetro deberían configurar? 
 
4. ¿Cuál es el comportamiento por defecto?

**Respuestas 📝:**

```
1. Cuando existen alumnos con el mismo promedio, estos comparten la misma posición en el ranking, generándose empates. Esto implica que varios estudiantes pueden ocupar el mismo lugar si sus promedios son iguales.

2. Para manejar esta situación, es necesario definir una estrategia de asignación de ranking en presencia de empates. En este caso, se utiliza el método "min", el cual asigna a todos los valores empatados la mejor posición disponible dentro del grupo. Esto significa que si dos estudiantes tienen el mejor promedio, ambos reciben el ranking 1, y el siguiente estudiante recibe el ranking correspondiente a la siguiente posición disponible (por ejemplo, 3).

3. El parámetro que se debe configurar para controlar este comportamiento es method dentro de la función rank() de pandas.

4. Por defecto, la función rank() utiliza el método "average", el cual asigna a los valores empatados el promedio de las posiciones que ocuparían.

```

---

### 1.3.4 Reprobados y Destacados 🏅

Contentos con su desempeño, la Universidad les solicita que identifiquen a los alumnos que han reprobado el año y a los que han tenido un desempeño destacado.

Para esto se considerará que:
- Un alumno ha **reprobado** cuando el promedio de notas chilenas (`mean_cl`) es inferior a 4.0
- Un alumno es **destacado** si posee notas chilenas superiores a 6.0 en `math_score_cl` y superiores a 6.3 en `reading_score_cl` y `writing_score_cl`


Cree las siguientes funciones:

1. [ ] `extract_failing` que retorne un DataFrame con solamente los alumnos que han reprobado en la prestigiosa universidad. [0.3 puntos]
2. [ ]  `sort_top` que extraiga los n (parametrizable) alumnos destacados, ordenados de mayor a menor promedio. [0.3 puntos]

**Respuesta:**

In [35]:
def extract_failing(df: pd.DataFrame) -> pd.DataFrame:
    return df[df["mean_cl"] < 4.0]


df_failing = extract_failing(df_cleaned)
display(df_failing)

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,math_score_cl,reading_score_cl,writing_score_cl,mean,mean_cl,rank
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0,3.22,3.76,3.76,43.00,3.58,960.0
13,Mikki Amaya,female,group A,high school,free/reduced,completed,34.0,48.0,41.0,3.04,3.88,3.46,41.00,3.46,965.0
26,Samuel Dougal,male,group C,master's degree,free/reduced,completed,46.0,42.0,46.0,3.76,3.52,3.76,44.67,3.68,947.0
55,Rodger Talavera,male,group B,high school,free/reduced,none,36.0,29.0,27.0,3.16,2.74,2.62,30.67,2.84,990.0
63,Morris Johnson,male,group A,associate's degree,free/reduced,completed,40.0,55.0,53.0,3.40,4.30,4.18,49.33,3.96,901.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1371,Charles Harian,male,group C,some high school,free/reduced,completed,45.0,52.0,49.0,3.70,4.12,3.94,48.67,3.92,911.0
1373,Wendy Gunnell,female,group D,some high school,free/reduced,none,27.0,34.0,32.0,2.62,3.04,2.92,31.00,2.86,989.0
1389,Diana Costa,female,group C,high school,free/reduced,none,41.0,46.0,43.0,3.46,3.76,3.58,43.33,3.60,956.0
1391,Amy Sieving,female,group C,high school,standard,none,29.0,29.0,30.0,2.74,2.74,2.80,29.33,2.76,994.0


In [36]:
def sort_top(df: pd.DataFrame, n: int) -> pd.DataFrame:
    
    destacados = df[
        (df["math_score_cl"] > 6.0) &
        (df["reading_score_cl"] > 6.3) &
        (df["writing_score_cl"] > 6.3)
    ]
    
    return destacados.sort_values(by="mean_cl", ascending=False).head(n)


df_top_students = sort_top(df_cleaned, n=10)
display(df_top_students)

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,math_score_cl,reading_score_cl,writing_score_cl,mean,mean_cl,rank
677,Richard Pryor,male,group E,bachelor's degree,standard,completed,100.0,100.0,100.0,7.00,7.00,7.00,100.00,7.00,1.0
384,Elizabeth Beasley,female,group E,bachelor's degree,standard,none,100.0,100.0,100.0,7.00,7.00,7.00,100.00,7.00,1.0
1352,Sandra Pompey,female,group E,associate's degree,standard,none,100.0,100.0,100.0,7.00,7.00,7.00,100.00,7.00,1.0
475,Emma Gray,female,group E,bachelor's degree,standard,completed,99.0,100.0,100.0,6.94,7.00,7.00,99.67,6.98,4.0
1276,Angela Cressey,female,group D,some college,standard,none,98.0,100.0,99.0,6.88,7.00,6.94,99.00,6.94,5.0
279,Emma Brasher,female,group D,some high school,standard,completed,97.0,100.0,100.0,6.82,7.00,7.00,99.00,6.94,5.0
1381,Robert Morrison,male,group D,some college,standard,completed,100.0,97.0,99.0,7.00,6.82,6.94,98.67,6.92,7.0
1219,Emmie Mooreland,female,group C,bachelor's degree,standard,completed,96.0,100.0,100.0,6.76,7.00,7.00,98.67,6.92,7.0
514,David Martinez,male,group E,associate's degree,free/reduced,completed,100.0,100.0,93.0,7.00,7.00,6.58,97.67,6.86,9.0
35,Shanna Braswell,female,group D,bachelor's degree,free/reduced,completed,93.0,100.0,100.0,6.58,7.00,7.00,97.67,6.86,9.0


---

### 1.3.5 Padres Helicóptero 👨‍👩‍👧

Algunos padres (extremadamente entrometidos) preocupados por el desempeño de sus hijos, desean saber si estos han aprobado o no el año. Como la tarea de buscar a mano cada uno de estos alumnos en el `DataFrame` resulta demasiado tedioso, el rector le solicita crear una función de consulta. 

Cree una función que:

1. Reciba el `DataFrame` y una lista con nombres de alumnos
2. Extraiga las notas chilenas de matemáticas, escritura, lectura y promedio general (`mean_cl`) de los alumnos listados en `student_list` [0.3 puntos]
3. Genere una nueva columna transitoria `is_failing` (**asegurarse de no agregarla al dataframe original**) cuyo valor sea `True` si el alumno está reprobando o `False` en caso contrario [0.3 puntos]
4. Ordene por promedio chileno, de mayor a menor [0.2 puntos]
5. Reinicie el índice para que este comience desde 0 [0.2 puntos]


**Hint:** Puede serle de utilidad utilizar `isin()`. Recuerde además usar una copia del dataframe original para no modificarlo con la nueva columna.

**Respuesta:**

In [38]:
def query_students(df: pd.DataFrame, student_list: list[str]) -> pd.DataFrame:
    
    # trabajar sobre copia
    df_copy = df.copy()
    
    # 1. filtrar estudiantes
    df_query = df_copy[df_copy["names"].isin(student_list)]
    
    # 2. seleccionar columnas necesarias
    df_query = df_query[
        ["names", "math_score_cl", "reading_score_cl", "writing_score_cl", "mean_cl"]
    ]
    
    # 3. columna transitoria is_failing
    df_query["is_failing"] = df_query["mean_cl"] < 4.0
    
    # 4. ordenar por promedio chileno (descendente)
    df_query = df_query.sort_values(by="mean_cl", ascending=False)
    
    # 5. resetear índice
    df_query = df_query.reset_index(drop=True)
    
    return df_query

In [39]:
student_list = [
    "Lucille Stanphill",
    "Marcus Mcfarland",
    "Matthew Freeman",
    "Dana Mojica",
    "Paul Hyder",
    "Jeffrey Korn",
    "Robert Strain",
    "Ronald Jett",
    "Lorena Reed",
    "Hazel Posey",
]

df_query = query_students(df_cleaned, student_list)
df_query

,names,math_score_cl,reading_score_cl,writing_score_cl,mean_cl,is_failing
0,Paul Hyder,6.70,5.86,6.04,6.20,False
1,Lucille Stanphill,5.86,6.04,5.92,5.94,False
2,Marcus Mcfarland,4.78,4.84,4.96,4.86,False
3,Jeffrey Korn,5.20,4.36,4.06,4.54,False
4,Robert Strain,4.30,4.66,4.24,4.40,False
5,Matthew Freeman,4.12,3.94,3.76,3.94,True
6,Dana Mojica,3.34,4.12,3.76,3.74,True
7,Lorena Reed,3.16,4.18,3.58,3.64,True
8,Ronald Jett,3.52,3.34,3.04,3.30,True
9,Hazel Posey,2.44,3.28,2.62,2.78,True


---

### 1.3.6 Categorías de Rendimiento 📊

El rector, intrigado por saber si existe una relación entre el nivel educacional de los padres y las notas de sus hijos, les plantea estudiar dicha relación mediante categorización de los datos. 

Para esto, se les solicita que implementen la función `get_categories`, donde se generen dos series con diferentes tipos de categorización a partir de los promedios chilenos (`mean_cl`):

- Una con `pd.cut` con las labels `["B1", "B2", "B3", "B4", "B5"]` [0.2 Puntos]
- Otra con `pd.qcut`, con las labels `["Q1", "Q2", "Q3", "Q4", "Q5"]` [0.2 Puntos]

La función debe retornar una tupla con ambas series. Después, usando indexadores apropiados, agreguen a `df_cleaned` las columnas `cut_cl` y `qcut_cl`.

**Respuesta:**

In [43]:
# En esta celda implementa la operación solicitada
def get_categories(df: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
    
    # cut (intervalos iguales)
    cut_cl = pd.cut(
        df["mean_cl"],
        bins=5,
        labels=["B1", "B2", "B3", "B4", "B5"]
    )
    
    # qcut (misma cantidad de datos por grupo)
    qcut_cl = pd.qcut(
        df["mean_cl"],
        q=5,
        labels=["Q1", "Q2", "Q3", "Q4", "Q5"]
    )
    
    return cut_cl, qcut_cl

In [45]:
#Ejecutar y agregar columnas
cut_cl, qcut_cl = get_categories(df_cleaned)

df_cleaned["cut_cl"] = cut_cl
df_cleaned["qcut_cl"] = qcut_cl

display(df_cleaned.head())

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,math_score_cl,reading_score_cl,writing_score_cl,mean,mean_cl,rank,cut_cl,qcut_cl
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0,3.22,3.76,3.76,43.00,3.58,960.0,B2,Q1
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0,5.80,5.68,5.86,79.67,5.78,199.0,B4,Q4
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0,5.38,4.96,4.78,67.33,5.04,534.0,B4,Q3
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0,5.86,5.50,5.56,77.33,5.64,255.0,B4,Q4
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0,6.64,6.16,6.22,89.00,6.34,59.0,B5,Q5


Hecho esto, grafique a través de un scatter plot el nivel educacional de los padres v/s el promedio chileno de los alumnos. Utilice los quintiles generados anteriormente (use la columna `qcut_cl`) para colorear los puntos y mostrar en qué quintil se encuentra cada dato.

**Pregunta: ❓** [0.3 Puntos]

> - ¿Qué diferencias hay entre las categorías generadas por `cut` y `qcut` (en términos conceptuales rangos-percentiles)?


**Respuesta 📝:**

```
En el caso de cut, los intervalos se construyen dividiendo el rango total de los valores en tramos de igual tamaño, por lo que cada categoría representa un rango fijo de valores. Sin embargo, esto no garantiza que cada grupo contenga la misma cantidad de observaciones, ya que depende de la distribución de los datos.

En qcut genera las categorías en función de los percentiles, dividiendo los datos en grupos con aproximadamente la misma cantidad de observaciones. Esto implica que los intervalos pueden tener distintos tamaños, pero aseguran una distribución equilibrada entre los grupos.

```

In [46]:
# Código para graficar
# Nota: asegúrese de que la columna qcut_cl esté creada antes de ejecutar esto

fig = px.scatter(
    df_cleaned.sort_values(by="mean_cl"),
    x="mean_cl",
    y="parental_level_of_education",
    hover_data=["gender"],
    color="qcut_cl",
    title="Promedio por Nivel de Educación de los Padres",
    labels={"mean_cl": "Promedio (Escala Chilena)", "parental_level_of_education": "Nivel Educacional de los Padres"},
    color_discrete_sequence=["tomato", "orange", "yellow", "greenyellow", "green"],
)

fig.show()

**Pregunta: ❓** [0.3 Puntos]

> - ¿Es posible visualizar alguna tendencia en el gráfico?


**Respuesta 📝:**

```

A partir del gráfico se puede observar una leve tendencia positiva entre el nivel educacional de los padres y el desempeño académico de los estudiantes, donde niveles educativos más altos, como bachelor’s degree o master’s degree, tienden a concentrar una mayor proporción de alumnos en los quintiles superiores de rendimiento (Q4 y Q5). Pero, esta relación no es concluyente, ya que existe una alta dispersión de los datos dentro de cada categoría, observándose estudiantes con distintos niveles de desempeño en todos los grupos educativos, así que, podrían existir otros factores influyentes.

```

---

# Conclusión

Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://gifdb.com/images/high/orange-cat-cat-walking-with-two-legs-xlgf7qx4i24da74f.gif" width="400">
</p>